version: "3"
services:
  mysql:
    image: mariadb:10.5.8
    container_name: db_mariadb
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./my-db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
